apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: DEMOEKS
  region: us-west-1

vpc:
  id: vpc-040d9e7433e95d7db
  cidr: "11.0.0.0/16"
  subnets:
    public:
      us-west-1c:
        id: subnet-04bb6351f47c8137b
        cidr: "11.0.1.0/24"
      us-west-1a:
        id: subnet-0c4c0a9d850484ac2
        cidr: "11.0.0.0/24"
    private:
      us-west-1c:
        id: subnet-00164d2b15dd3a4ac
        cidr: "11.0.3.0/24"
      us-west-1a:
        id: subnet-069346d37acf45474
        cidr: "11.0.2.0/24"
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      # new feature for restricting SSH access to certain AWS security group IDs
    #  sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
  - name: managed-ng-2
    instanceType: t3.medium
    privateNetworking: true
    minSize: 2
    maxSize: 3

