apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: DEMO
  region: us-east-1

vpc:
  id: vpc-012ea99e21f5b6cf8
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-05d09bb1f611d2a38
        cidr: "10.0.1.0/24"
      us-east-1c:
        id: subnet-0014b72ad0eeb4f96
        cidr: "10.0.3.0/24"
    private:
      us-east-1a:
        id: subnet-02267fade1103b108
        cidr: "10.0.2.0/24"
      us-east-1c:
        id: subnet-040f54e9b1831222d
        cidr: "10.0.0.0/25"

nodeGroups:
  - name: public-workers-1
    iam:
      instanceProfileARN: "arn:aws:iam::469134739746:instance-profile/cluster-worker-role"
      instanceRoleARN: "arn:aws:iam::469134739746:role/cluster-worker-role"
    instanceType: t3.medium
    desiredCapacity: 1
    # ssh:
    #   allow: true
  - name: public-workers-2
    iam:
      instanceProfileARN: "arn:aws:iam::469134739746:instance-profile/cluster-worker-role"
      instanceRoleARN: "arn:aws:iam::469134739746:role/cluster-worker-role"
    instanceType: t3.medium
    desiredCapacity: 1
    # ssh:
    #   allow: true
  - name: private-workers
    iam:
      instanceProfileARN: "arn:aws:iam::469134739746:instance-profile/cluster-worker-role"
      instanceRoleARN: "arn:aws:iam::469134739746:role/cluster-worker-role"
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true